set(MINIDLNA_LIBS_DEPS )
set(MINIDLNA_INCL_DEPS )

find_package(Libevent REQUIRED)

list(APPEND MINIDLNA_LIBS_DEPS ${Libevent_LIBRARIES})
list(APPEND MINIDLNA_INCL_DEPS ${Libevent_INCLUDE_DIR})

find_package(SQLite3 REQUIRED)

list(APPEND MINIDLNA_LIBS_DEPS ${SQLite3_LIBRARIES})
list(APPEND MINIDLNA_INCL_DEPS ${SQLite3_INCLUDE_DIRS})


find_package(JPEG REQUIRED)

list(APPEND MINIDLNA_LIBS_DEPS ${JPEG_LIBRARIES})
list(APPEND MINIDLNA_INCL_DEPS ${JPEG_INCLUDE_DIRS})


find_package(EXIF REQUIRED)

list(APPEND MINIDLNA_LIBS_DEPS ${EXIF_LIBRARIES})
list(APPEND MINIDLNA_INCL_DEPS ${EXIF_INCLUDE_DIRS})

find_package(FFmpeg REQUIRED)
list(APPEND MINIDLNA_LIBS_DEPS ${FFmpeg_LIBRARIES})
list(APPEND MINIDLNA_INCL_DEPS ${FFmpeg_INCLUDE_DIRS})


find_package(Vorbis REQUIRED)
list(APPEND MINIDLNA_LIBS_DEPS ${VORBIS_LIBRARY})
list(APPEND MINIDLNA_INCL_DEPS ${VORBIS_INCLUDE_DIRS})

list(APPEND MINIDLNA_LIBS_DEPS ${OGG_LIBRARY})
list(APPEND MINIDLNA_INCL_DEPS ${OGG_INCLUDE_DIR})

find_package(id3tag REQUIRED)
list(APPEND MINIDLNA_LIBS_DEPS ${id3tag_LIBRARIES})
list(APPEND MINIDLNA_INCL_DEPS ${id3tag_INCLUDE_DIR})

find_package(FLAC REQUIRED)
list(APPEND MINIDLNA_LIBS_DEPS ${FLAC_LIBRARIES})
list(APPEND MINIDLNA_INCL_DEPS ${FLAC_INCLUDE_DIR})
